"""
Copyright 2020-2026 Broadwell Consulting Inc.

"Serial Wombat" is a registered trademark of Broadwell Consulting Inc. in
the United States.  See SerialWombat.com for usage guidance.

Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
"""

"""! @file SerialWombatErrors.py

Error constants matching SerialWombatErrors.h in the Arduino library.
"""

SW_ERROR_UNNUMBERED_ERROR = 32767
SW_ERROR_PINS_MUST_BE_ON_SAME_PORT = 1
SW_ERROR_ASCII_NUMBER_TOO_BIG_16 = 2
SW_ERROR_UNKNOWN_PIN_MODE = 3
SW_ERROR_RESET_STRING_INCORRECT = 4
SW_ERROR_INVALID_COMMAND = 5
SW_ERROR_INSUFFICIENT_SPACE = 6
SW_ERROR_WUB_COUNT_GT_4 = 7
SW_ERROR_WUB_INVALID_ADDRESS = 8
SW_ERROR_WUB_CONTINUE_OUTOFBOUNDS = 9
SW_ERROR_RF_ODD_ADDRESS = 10
SW_ERROR_FLASH_WRITE_INVALID_ADDRESS = 11
SW_ERROR_INVALID_PIN_COMMAND = 12
SW_ERROR_PIN_CONFIG_WRONG_ORDER = 13
SW_ERROR_WS2812_INDEX_GT_LEDS = 14
SW_ERROR_PIN_NOT_CAPABLE = 15
SW_ERROR_HW_RESOURCE_IN_USE = 16
SW_ERROR_INVALID_PARAMETER_3 = 17
SW_ERROR_INVALID_PARAMETER_4 = 18
SW_ERROR_INVALID_PARAMETER_5 = 19
SW_ERROR_INVALID_PARAMETER_6 = 20
SW_ERROR_INVALID_PARAMETER_7 = 21
SW_ERROR_PIN_NUMBER_TOO_HIGH = 22
SW_ERROR_PIN_IS_COMM_INTERFACE = 23
SW_ERROR_ANALOG_CAL_WRONG_UNLOCK = 24
SW_ERROR_2ND_INF_WRONG_UNLOCK = 25
SW_ERROR_2ND_INF_UNAVAILABLE = 26
SW_ERROR_UART_NOT_INITIALIZED = 27
SW_ERROR_CMD_BYTE_1 = 28
SW_ERROR_CMD_BYTE_2 = 29
SW_ERROR_CMD_BYTE_3 = 30
SW_ERROR_CMD_BYTE_4 = 31
SW_ERROR_CMD_BYTE_5 = 32
SW_ERROR_CMD_BYTE_6 = 33
SW_ERROR_CMD_BYTE_7 = 34
SW_ERROR_CMD_UNSUPPORTED_BAUD_RATE = 35
SW_ERROR_QUEUE_RESULT_INSUFFICIENT_USER_SPACE = 36
SW_ERROR_QUEUE_RESULT_UNALIGNED_ADDRESS = 37
SW_ERROR_QUEUE_RESULT_INVALID_QUEUE = 38
SW_ERROR_QUEUE_RESULT_FULL = 39
SW_ERROR_QUEUE_RESULT_EMPTY = 40
SW_ERROR_DATA_NOT_AVAILABLE = 41
SW_ERROR_TM1637_WRONG_MODE = 42
SW_ERROR_RUB_INVALID_ADDRESS = 43
SW_ERROR_UNKNOWN_OUTPUTSCALE_COMMAND = 44
SW_ERROR_UNKNOWN_INPUT_PROCESS_COMMAND = 45
SW_ERROR_PULSE_ON_CHANGE_ENTRY_OUT_OF_RANGE = 46
SW_ERROR_PULSE_ON_CHANGE_UNKNOWN_MODE = 47
SW_ERROR_LESS_THAN_8_BYTES_RETURNED = 48
SW_ERROR_REENTRANCY_NOT_SUPPORTED = 49
SW_ERROR_CLASS_INIITALIZATION_ERROR = 50
SW_ERROR_WRONG_CHIP_TYPE = 51
SW_ERROR_WRONG_CHIP_FIRMWARE_VERSION = 52
