# Converted from PinModes/VGA/VGA_Ex02_Colors/VGA_Ex02_Colors.ino
import SerialWombat
from ArduinoFunctions import delay, delayMicroseconds, millis

# Import constants from the SerialWombat module so names match the Arduino examples.
for _name in dir(SerialWombat.SerialWombatPinMode_t):
    if _name.startswith("PIN_MODE_"):
        globals()[_name] = getattr(SerialWombat.SerialWombatPinMode_t, _name)
for _name in dir(SerialWombat.SerialWombatDataSource):
    if _name.startswith("SW_DATA_"):
        globals()[_name] = getattr(SerialWombat.SerialWombatDataSource, _name)
PERIOD_1mS = 0; PERIOD_2mS = 1; PERIOD_4mS = 2; PERIOD_8mS = 3; PERIOD_16mS = 4; PERIOD_32mS = 5; PERIOD_64mS = 6; PERIOD_128mS = 7; PERIOD_256mS = 8; PERIOD_512mS = 9; PERIOD_1024mS = 10
HC_SR04 = 0
RAW = 0; AVERAGE = 1; FILTERED = 2; MINIMUM = 3; MAXIMUM = 4
DATACOUNT = 2; ADDRESS = 3; COMMAND = 4

#Comment these lines in if you're connecting directly to a Serial Wombat Chip's UART through cPython serial Module
#Change the parameter of SerialWombatChip_cpy_serial to match the name of your Serial port
#import SerialWombat_cpy_serial
#sw = SerialWombat_cpy_serial.SerialWombatChip_cpy_serial("COM25")

#Comment these lines in if you're connecting to a Serial Wombat Chip's I2C port using cPython smbus2
#Change busNumber and swI2Caddress to match your configuration
#import SerialWombat_smbus2_i2c
#busNumber = 1
#swI2Caddress = 0x6B
#sw = SerialWombat_smbus2_i2c.SerialWombatChip_smbus2_i2c(busNumber, swI2Caddress)

#Comment these lines in if you're connecting to a Serial Wombat Chip's I2C port using CircuitPython's I2C interface
#Change sclPin, sdaPin, and swI2Caddress to match your configuration
#import board
#import busio
#import SerialWombat_cp_i2c
#swI2Caddress = 0x6B
#i2c = busio.I2C(board.SCL, board.SDA)
#sw = SerialWombat_cp_i2c.SerialWombatChip_cp_i2c(i2c, swI2Caddress)

#Comment these lines in if you're connecting to a Serial Wombat Chip's I2C port using Micropython's I2C interface
#Change the values for sclPin, sdaPin, and swI2Caddress to match your configuration
#import machine
#import SerialWombat_mp_i2c
#sclPin = 22
#sdaPin = 21
#swI2Caddress = 0x6B
#i2c = machine.I2C(0,
#            scl=machine.Pin(sclPin),
#            sda=machine.Pin(sdaPin),
#            freq=100000,timeout = 50000)
#sw = SerialWombat_mp_i2c.SerialWombatChip_mp_i2c(i2c,swI2Caddress)
#sw.address = swI2Caddress

#Comment these lines in if you're connecting to a Serial Wombat Chip's UART port using Micropython's UART interface
#Change the values for UARTnum, txPin, and rxPin to match your configuration
import machine
import SerialWombat_mp_UART
txPin = 12
rxPin = 14
UARTnum = 2
uart = machine.UART(UARTnum, baudrate=115200, tx=txPin, rx=rxPin)
sw = SerialWombat_mp_UART.SerialWombatChipUART(uart)

#Interface independent code starts here:
import SerialWombat18ABVGA

#
#This example shows how to configure pins 14-18 of the Serial Wombat 18AB chip to output VGA,
#and display different colored text on different lines using text generated by the
#AdafruitGFX library, the SerialWombat18ABVGA pin mode, and the SerialWombat18ABVGADriver
#wrapper to provide AdaFruitGFX compatible interfaces.
#
#We will display the words Red, Blue, Green, Cyan, Magenta, Yellow and White in their colors.
#
#Note that colors need to be set for an entire line of pixels, and that color handling is done
#through the Serial Wombat 18AB Pin mode, not the color functions of the AdafruitGFX display.
#You can almost think of it as putting a tinted color transparency over the screen at the
#driver layer.  Any of you kids ever play VecTrex?
#
#Serial Wombat 18AB Firmware 2.1 or later is needed to use this example.
#
#This example assumes a Serial Wombat 18AB chip is attached to the Arduino board via I2C.
#In this case we're assuming an ESP-01 module with I2C Data and Clock lines on ESP-02 pins 2 and 0.
#
#Connections:
#VGA VSYNC (VGA Pin 14) -> 100 ohm Resistor -> SW Pin 18
#VGA HSYNC (VGA Pin 13) -> 100 ohm Resistor ->SW Pin 17
#VGA Red   (VGA Pin 1) -> 280 ohm Resistor -> SW Pin 16
#VGA Green (VGA Pin 2) -> 280 ohm Resistor -> SW Pin 15
#VGA Blue (VGA Pin 3) -> 280 ohm Resistor -> SW Pin 14
#
#A video demonstrating the use of the VGA pin mode on the Serial Wombat 18AB chip is available at:
#https://youtu.be/DcOSat8VybA
#
#Documentation for the VGA class is available at:
#https://broadwellconsultinginc.github.io/SerialWombatArdLib/class_serial_wombat18_a_b_v_g_a.html
#
#

# sw is provided by the selected interface block above
vgaDriver = SerialWombat18ABVGA.SerialWombat18ABVGA(sw)
# TODO_MANUAL_CONVERSION: SerialWombat18ABVGADriver vgaDisplay(vgaDriver)


def setup():
  # put your setup code here, to run once:
  # Wire.begin() is handled by the selected Python interface block

  # Serial.begin() is not used in this Python example
  delay(3000)
  print("High Speed Clock Example")


  sw.begin()  # Python interface was configured above

  #Optional Error handling code begin:
  if not sw.isSW18():
    print("This Example is not supported on the Serial Wombat 4B or 8B chip.  An  18AB chip is required.")
    while True:
      delay(100)
  if not sw.isLatestFirmware():
    print("Firmware version mismatch.  Download latest Serial Wombat Arduino Library and update Serial Wombat Firmware to latest version")

  sw.registerErrorHandler(SerialWombatSerialErrorHandlerBrief);  #Register an error handler that will print communication errors to Serial
  #Optional Error handling code end


  vgaDriver.begin(18, 0x0000)

  showGraphicAndText()

def loop():
  # put your main code here, to run repeatedly:
    pass



LINEHEIGHT = 8  # Based on the size of the font
def showGraphicAndText():
  vgaDisplay.fillScreen(0)
  vgaDisplay.setCursor(0, 0)
  vgaDisplay.setTextSize(2)

  vgaDisplay.println("RED")
  vgaDisplay.println("GREEN")
  vgaDisplay.println("BLUE")
  vgaDisplay.println("CYAN")
  vgaDisplay.println("MAGENTA")
  vgaDisplay.println("YELLOW")
  vgaDisplay.println("WHITE")

  vgaDriver.setLineColor(4, 0, LINEHEIGHT * 2);  # 4 = Red
  vgaDriver.setLineColor(2, LINEHEIGHT * 2, LINEHEIGHT * 4);  # 2 = Green
  vgaDriver.setLineColor(1, LINEHEIGHT * 4, LINEHEIGHT * 6);  # 1 = Blue
  vgaDriver.setLineColor(3, LINEHEIGHT * 6, LINEHEIGHT * 8);  # 3 = Cyan
  vgaDriver.setLineColor(5, LINEHEIGHT * 8, LINEHEIGHT * 10);  # 5 = Magenta
  vgaDriver.setLineColor(6, LINEHEIGHT * 10, LINEHEIGHT * 12);  # 6 = Yellow
  vgaDriver.setLineColor(7, LINEHEIGHT * 12, LINEHEIGHT * 14);  # 7 = White


setup()
while True:
    loop()
