# Converted from PinModes/VGA/VGA_Ex04_WebBillboard/VGA_Ex04_WebBillboard.ino
import SerialWombat
from ArduinoFunctions import delay, delayMicroseconds, millis

# Import constants from the SerialWombat module so names match the Arduino examples.
for _name in dir(SerialWombat.SerialWombatPinMode_t):
    if _name.startswith("PIN_MODE_"):
        globals()[_name] = getattr(SerialWombat.SerialWombatPinMode_t, _name)
for _name in dir(SerialWombat.SerialWombatDataSource):
    if _name.startswith("SW_DATA_"):
        globals()[_name] = getattr(SerialWombat.SerialWombatDataSource, _name)
PERIOD_1mS = 0; PERIOD_2mS = 1; PERIOD_4mS = 2; PERIOD_8mS = 3; PERIOD_16mS = 4; PERIOD_32mS = 5; PERIOD_64mS = 6; PERIOD_128mS = 7; PERIOD_256mS = 8; PERIOD_512mS = 9; PERIOD_1024mS = 10
HC_SR04 = 0
RAW = 0; AVERAGE = 1; FILTERED = 2; MINIMUM = 3; MAXIMUM = 4
DATACOUNT = 2; ADDRESS = 3; COMMAND = 4

#Comment these lines in if you're connecting directly to a Serial Wombat Chip's UART through cPython serial Module
#Change the parameter of SerialWombatChip_cpy_serial to match the name of your Serial port
#import SerialWombat_cpy_serial
#sw = SerialWombat_cpy_serial.SerialWombatChip_cpy_serial("COM25")

#Comment these lines in if you're connecting to a Serial Wombat Chip's I2C port using cPython smbus2
#Change busNumber and swI2Caddress to match your configuration
#import SerialWombat_smbus2_i2c
#busNumber = 1
#swI2Caddress = 0x6B
#sw = SerialWombat_smbus2_i2c.SerialWombatChip_smbus2_i2c(busNumber, swI2Caddress)

#Comment these lines in if you're connecting to a Serial Wombat Chip's I2C port using CircuitPython's I2C interface
#Change sclPin, sdaPin, and swI2Caddress to match your configuration
#import board
#import busio
#import SerialWombat_cp_i2c
#swI2Caddress = 0x6B
#i2c = busio.I2C(board.SCL, board.SDA)
#sw = SerialWombat_cp_i2c.SerialWombatChip_cp_i2c(i2c, swI2Caddress)

#Comment these lines in if you're connecting to a Serial Wombat Chip's I2C port using Micropython's I2C interface
#Change the values for sclPin, sdaPin, and swI2Caddress to match your configuration
#import machine
#import SerialWombat_mp_i2c
#sclPin = 22
#sdaPin = 21
#swI2Caddress = 0x6B
#i2c = machine.I2C(0,
#            scl=machine.Pin(sclPin),
#            sda=machine.Pin(sdaPin),
#            freq=100000,timeout = 50000)
#sw = SerialWombat_mp_i2c.SerialWombatChip_mp_i2c(i2c,swI2Caddress)
#sw.address = swI2Caddress

#Comment these lines in if you're connecting to a Serial Wombat Chip's UART port using Micropython's UART interface
#Change the values for UARTnum, txPin, and rxPin to match your configuration
import machine
import SerialWombat_mp_UART
txPin = 12
rxPin = 14
UARTnum = 2
uart = machine.UART(UARTnum, baudrate=115200, tx=txPin, rx=rxPin)
sw = SerialWombat_mp_UART.SerialWombatChipUART(uart)

#Interface independent code starts here:
import SerialWombat18ABVGA

#
#This example shows how to configure pins 14-18 of the Serial Wombat 18AB chip to output VGA,
#and display different colored text on different lines using text generated by the
#AdafruitGFX library, the SerialWombat18ABVGA pin mode, and the SerialWombat18ABVGADriver
#wrapper to provide AdaFruitGFX compatible interfaces.
#
#We will display the words Red, Blue, Green, Cyan, Magenta, Yellow and White in their colors.
#
#Note that colors need to be set for an entire line of pixels, and that color handling is done
#through the Serial Wombat 18AB Pin mode, not the color functions of the AdafruitGFX display.
#You can almost think of it as putting a tinted color transparency over the screen at the
#driver layer.  Any of you kids ever play VecTrex?
#
#Serial Wombat 18AB Firmware 2.1 or later is needed to use this example.
#
#This example assumes a Serial Wombat 18AB chip is attached to the Arduino board via I2C.
#In this case we're assuming an ESP-01 module with I2C Data and Clock lines on ESP-02 pins 2 and 0.
#
#Connections:
#VGA VSYNC (VGA Pin 14) -> 100 ohm Resistor -> SW Pin 18
#VGA HSYNC (VGA Pin 13) -> 100 ohm Resistor ->SW Pin 17
#VGA Red   (VGA Pin 1) -> 280 ohm Resistor -> SW Pin 16
#VGA Green (VGA Pin 2) -> 280 ohm Resistor -> SW Pin 15
#VGA Blue (VGA Pin 3) -> 280 ohm Resistor -> SW Pin 14
#
#A video demonstrating the use of the VGA pin mode on the Serial Wombat 18AB chip is available at:
#https://youtu.be/DcOSat8VybA
#
#Documentation for the VGA class is available at:
#https://broadwellconsultinginc.github.io/SerialWombatArdLib/class_serial_wombat18_a_b_v_g_a.html
#
#

# TODO_MANUAL_CONVERSION: const char* ssid     = "BILLBOARD"
# TODO_MANUAL_CONVERSION: const char* password = "123456789"

# Set web server port number to 80
# TODO_MANUAL_CONVERSION: WiFiServer server(80)
# Variable to store the HTTP request
header = 0

# sw is provided by the selected interface block above
vgaDriver = SerialWombat18ABVGA.SerialWombat18ABVGA(sw)
# TODO_MANUAL_CONVERSION: SerialWombat18ABVGADriver vgaDisplay(vgaDriver)
IP = IPAddress()

def setup():
  # put your setup code here, to run once:
  # Wire.begin() is handled by the selected Python interface block

  # Serial.begin() is not used in this Python example
  delay(3000)
  print("High Speed Clock Example")


  sw.begin()  # Python interface was configured above

  #Optional Error handling code begin:
  if not sw.isSW18():
    print("This Example is not supported on the Serial Wombat 4B or 8B chip.  An  18AB chip is required.")
    while True:
      delay(100)
  if not sw.isLatestFirmware():
    print("Firmware version mismatch.  Download latest Serial Wombat Arduino Library and update Serial Wombat Firmware to latest version")

  sw.registerErrorHandler(SerialWombatSerialErrorHandlerBrief);  #Register an error handler that will print communication errors to Serial
  #Optional Error handling code end


  # Connect to Wi-Fi network with SSID and password
  print("Setting AP (Access Point)", end="")
  # Remove the password parameter, if you want the AP (Access Point) to be open
  WiFi.softAP(ssid, password)

  IP = WiFi.softAPIP()
  server.begin()
  vgaDriver.begin(18, 0x0000)

  showGraphicAndText()

def loop():
  # put your main code here, to run repeatedly:
  client = server.available()  # Listen for incoming clients

  if client:
    # If a new client connects,
    Serial.println("New Client.");  # print a message out in the serial port
    currentLine = ""  # make a String to hold incoming data from the client
    while client.connected():
      # loop while the client's connected
      if client.available():
        # if there's bytes to read from the client,
        c = client.read()  # read a byte, then
        # Serial.write(c);                    // print it out the serial monitor
        header += c
        if c == '\n':
          # if the byte is a newline character
          # if the current line is blank, you got two newline characters in a row.
          # that's the end of the client HTTP request, so send a response:
          if currentLine.length() == 0:
            # HTTP headers always start with a response code (e.g. HTTP/1.1 200 OK)
            # and a content-type so the client knows what's coming, then a blank line:
            client.println("HTTP/1.1 200 OK")
            client.println("Content-type:text/html")
            client.println("Connection: close")
            client.println()
            index = 0

            index = header.indexOf("=")
            print("++++++++++++++++++++++++++++++++++++++++++++++")
            print(header)
            print("++++++++++++++++++++++++++++++++++++++++++++++")
            print("="); Serial.println(index, end="")
            endOfFirstLine = header.indexOf("\n")
            if index >= 0  and  index < endOfFirstLine:
              vgaDisplay.fillScreen(0)
              vgaDisplay.setCursor(0, 0)
            while index >= 0  and  index < endOfFirstLine:
              end = header.indexOf("",index + 1)
              print(""); Serial.println(end, end="")
              if end == -1  or  end > endOfFirstLine:
                end = header.indexOf(" HTTP", index)
                if end == -1:
                  end = index + 1
                print(" HTTP "); Serial.println(end, end="")

              s = header.substring(index + 1,end)
              s.replace("+"," ")
              print(s)
              vgaDisplay.println(s)
              index = header.indexOf("=",end)
              print("="); Serial.println(index, end="")



            # Display the HTML web page
            # TODO_MANUAL_CONVERSION: client.println(R"JFIE(
            # TODO_MANUAL_CONVERSION: <not DOCTYPE html><html>
            # TODO_MANUAL_CONVERSION: <head><meta name="viewport" content="width=device-width, initial-scale=1">
            # TODO_MANUAL_CONVERSION: <link rel="icon" href="data:,">
            # TODO_MANUAL_CONVERSION: <style>html {
              # TODO_MANUAL_CONVERSION: font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center
            # TODO_MANUAL_CONVERSION: .button {
              # TODO_MANUAL_CONVERSION: background-color: #4CAF50; border: none; color: white; padding: 16px 40px
              # TODO_MANUAL_CONVERSION: text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer
            # TODO_MANUAL_CONVERSION: .button2 {
              # TODO_MANUAL_CONVERSION: background-color: #555555
            # TODO_MANUAL_CONVERSION: </style></head> )JFIE")

            # Web Page Heading
            client.println("<body><h1>VGA Billboard</h1>")

            # TODO_MANUAL_CONVERSION: client.println(R"JFIE(
            # TODO_MANUAL_CONVERSION: <form action="/action_page.php">
            # TODO_MANUAL_CONVERSION: <input type="text" id="fname" name="L0" value="Serial Wombat"><br><br>
            # TODO_MANUAL_CONVERSION: <input type="text" id="lname" name="L1" value="18AB VGA"><br><br>
            # TODO_MANUAL_CONVERSION: <input type="text" id="lname" name="L2" value="BillBoard"><br><br>
            # TODO_MANUAL_CONVERSION: <input type="text" id="lname" name="L3" value="Demo"><br><br>
            # TODO_MANUAL_CONVERSION: <input type="text" id="lname" name="L4" value="Broadwell"><br><br>
            # TODO_MANUAL_CONVERSION: <input type="text" id="lname" name="L5" value="Consulting"><br><br>
            # TODO_MANUAL_CONVERSION: <input type="text" id="lname" name="L6" value="Inc."><br><br>
            # TODO_MANUAL_CONVERSION: <input type="submit" value="Submit">
            # TODO_MANUAL_CONVERSION: </form> )JFIE")
            client.println("</body></html>")

            # The HTTP response ends with another blank line
            client.println()
            # Break out of the while loop
            break
          else:
            # if you got a newline, then clear currentLine
            currentLine = ""
        elif c != '\r':
          # if you got anything else but a carriage return character,
          currentLine += c;  # add it to the end of the currentLine
    # Clear the header variable
    header = ""
    # Close the connection
    client.stop()
    print("Client disconnected.")
    print("")



LINEHEIGHT = 8  # Based on the size of the font
def showGraphicAndText():
  vgaDisplay.fillScreen(0)
  vgaDisplay.setCursor(0, 0)
  vgaDisplay.setTextSize(2)


  vgaDisplay.println(IP)

  vgaDriver.setLineColor(4, 0, LINEHEIGHT * 2);  # 4 = Red
  vgaDriver.setLineColor(2, LINEHEIGHT * 2, LINEHEIGHT * 4);  # 2 = Green
  vgaDriver.setLineColor(1, LINEHEIGHT * 4, LINEHEIGHT * 6);  # 1 = Blue
  vgaDriver.setLineColor(3, LINEHEIGHT * 6, LINEHEIGHT * 8);  # 3 = Cyan
  vgaDriver.setLineColor(5, LINEHEIGHT * 8, LINEHEIGHT * 10);  # 5 = Magenta
  vgaDriver.setLineColor(6, LINEHEIGHT * 10, LINEHEIGHT * 12);  # 6 = Yellow
  vgaDriver.setLineColor(7, LINEHEIGHT * 12, LINEHEIGHT * 14);  # 7 = White


setup()
while True:
    loop()
