# Converted from PinModes/VGA/VGA_Ex04_WebBillboard/VGA_Ex04_WebBillboard.ino
# PORTING NOTE — REFERENCE PORT
# Network host adaptation required.
# Uses Arduino Wi-Fi server and String/IPAddress APIs in addition to Serial Wombat VGA calls. Replace the web-server layer with the selected Python runtime network stack.
# This file is syntactically valid Python, but it is not expected to run until those host-platform dependencies are supplied.

import SerialWombat
from ArduinoFunctions import delay, delayMicroseconds, millis

import SerialWombat_interface
# >>> IMPORTANT: Set this to the configured I2C address of your Serial Wombat chip.
SERIAL_WOMBAT_ADDRESS = 0x6B
sw = SerialWombat_interface.SerialWombatChipInstance(SERIAL_WOMBAT_ADDRESS)


# Interface independent code starts here:
import SerialWombat18ABVGA

# ===== Arduino tab: VGA_Ex04_WebBillboard.ino =====
#
# This example shows how to configure pins 14-18 of the Serial Wombat 18AB chip to output VGA,
# and display different colored text on different lines using text generated by the
# AdafruitGFX library, the SerialWombat18ABVGA pin mode, and the SerialWombat18ABVGADriver
# wrapper to provide AdaFruitGFX compatible interfaces.
#
# We will display the words Red, Blue, Green, Cyan, Magenta, Yellow and White in their colors.
#
# Note that colors need to be set for an entire line of pixels, and that color handling is done
# through the Serial Wombat 18AB Pin mode, not the color functions of the AdafruitGFX display.
# You can almost think of it as putting a tinted color transparency over the screen at the
# driver layer.  Any of you kids ever play VecTrex?
#
# Serial Wombat 18AB Firmware 2.1 or later is needed to use this example.
#
# This example assumes a Serial Wombat 18AB chip is attached to the Arduino board via I2C.
# In this case we're assuming an ESP-01 module with I2C Data and Clock lines on ESP-02 pins 2 and 0.
#
# Connections:
# VGA VSYNC (VGA Pin 14) -> 100 ohm Resistor -> SW Pin 18
# VGA HSYNC (VGA Pin 13) -> 100 ohm Resistor ->SW Pin 17
# VGA Red   (VGA Pin 1) -> 280 ohm Resistor -> SW Pin 16
# VGA Green (VGA Pin 2) -> 280 ohm Resistor -> SW Pin 15
# VGA Blue (VGA Pin 3) -> 280 ohm Resistor -> SW Pin 14
#
# A video demonstrating the use of the VGA pin mode on the Serial Wombat 18AB chip is available at:
# https://youtu.be/DcOSat8VybA
#
# Documentation for the VGA class is available at:
# https://broadwellconsultinginc.github.io/SerialWombatArdLib/class_serial_wombat18_a_b_v_g_a.html
#
ssid = "BILLBOARD"
password = "123456789"
# Set web server port number to 80
server = WiFiServer(80)
# Variable to store the HTTP request
header = String()
# sw is provided by the selected Python interface block above
vgaDriver = SerialWombat18ABVGA.SerialWombat18ABVGA(sw)
vgaDisplay = SerialWombat18ABVGA.SerialWombat18ABVGADriver(vgaDriver)
IP = IPAddress()
def setup():
  global IP
  # put your setup code here, to run once:
  # Wire.begin() is handled by the selected Python interface block
  # Initialize the I2C Bus on default pins
  # Serial.begin() is not used in this Python example
  delay(3000)
  print("High Speed Clock Example")
  sw.begin()  # Python interface was configured above
  # Scan the bus for Serial Wombat chips, and initialize the first one found
  # Optional Error handling code begin:
  if not sw.isSW18():
    print("This Example is not supported on the Serial Wombat 4B or 8B chip. An 18AB chip is required.")
    while 1:
      delay(100)
  if not sw.isLatestFirmware():
    print("Firmware version mismatch. Download latest Serial Wombat Arduino Library and update Serial Wombat Firmware to latest version")
  # sw.registerErrorHandler(...) is Arduino-specific; Python errors are returned by library calls
  # Register an error handler that will print communication errors to Serial
  # Optional Error handling code end
  # Connect to Wi-Fi network with SSID and password
  print("Setting AP (Access Point)", end="")
  # Remove the password parameter, if you want the AP (Access Point) to be open
  WiFi.softAP(ssid, password)
  IP = WiFi.softAPIP()
  server.begin()
  vgaDriver.begin(18, 0x0000)
  showGraphicAndText()
def loop():
  global header
  # put your main code here, to run repeatedly:
  client = server.available()
  # Listen for incoming clients
  if client:
    # If a new client connects,
    print("New Client.")
    # print a message out in the serial port
    currentLine = ""
    # make a String to hold incoming data from the client
    while client.connected():
      # loop while the client's connected
      if client.available():
        # if there's bytes to read from the client,
        c = client.read()
        # read a byte, then
        # Serial.write(c);                    // print it out the serial monitor
        header += c
        if c == '\n':
          # if the byte is a newline character
          # if the current line is blank, you got two newline characters in a row.
          # that's the end of the client HTTP request, so send a response:
          if len(currentLine) == 0:
            # HTTP headers always start with a response code (e.g. HTTP/1.1 200 OK)
            # and a content-type so the client knows what's coming, then a blank line:
            client.println("HTTP/1.1 200 OK")
            client.println("Content-type:text/html")
            client.println("Connection: close")
            client.println()
            index = 0
            index = header.indexOf("=")
            print("++++++++++++++++++++++++++++++++++++++++++++++")
            print(header)
            print("++++++++++++++++++++++++++++++++++++++++++++++")
            print("=", end="")
            print(index)
            endOfFirstLine = header.indexOf("\n")
            if index >= 0 and index < endOfFirstLine:
              vgaDisplay.fillScreen(0)
              vgaDisplay.setCursor(0, 0)
            while index >= 0 and index < endOfFirstLine:
              end = header.indexOf("&",index + 1)
              print("&", end="")
              print(end)
              if end == -1 or end > endOfFirstLine:
                end = header.indexOf(" HTTP", index)
                if end == -1:
                  end = index + 1
                print(" HTTP ", end="")
                print(end)
              s = header.substring(index + 1,end)
              s.replace("+"," ")
              print(s)
              vgaDisplay.println(s)
              index = header.indexOf("=",end)
              print("=", end="")
              print(index)
            # Display the HTML web page
            client.println(' <!DOCTYPE html><html> <head><meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="icon" href="data:,"> <style>html [ font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center;] .button [ background-color: #4CAF50; border: none; color: white; padding: 16px 40px; text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer;] .button2 [background-color: #555555;]</style></head> ')
            # Web Page Heading
            client.println("<body><h1>VGA Billboard</h1>")
            client.println(' <form action="/action_page.php"> <input type="text" id="fname" name="L0" value="Serial Wombat"><br><br> <input type="text" id="lname" name="L1" value="18AB VGA"><br><br> <input type="text" id="lname" name="L2" value="BillBoard"><br><br> <input type="text" id="lname" name="L3" value="Demo"><br><br> <input type="text" id="lname" name="L4" value="Broadwell"><br><br> <input type="text" id="lname" name="L5" value="Consulting"><br><br> <input type="text" id="lname" name="L6" value="Inc."><br><br> <input type="submit" value="Submit"> </form> ')
            client.println("</body></html>")
            # The HTTP response ends with another blank line
            client.println()
            # Break out of the while loop
            break
          else:
            # if you got a newline, then clear currentLine
            currentLine = ""
        elif c != '\r':
          # if you got anything else but a carriage return character,
          currentLine += c
          # add it to the end of the currentLine
    # Clear the header variable
    header = ""
    # Close the connection
    client.stop()
    print("Client disconnected.")
    print("")
LINEHEIGHT = 8  # Based on the size of the font
def showGraphicAndText():
  vgaDisplay.fillScreen(0)
  vgaDisplay.setCursor(0, 0)
  vgaDisplay.setTextSize(2)
  vgaDisplay.println(IP)
  vgaDriver.setLineColor(4, 0, LINEHEIGHT * 2)
  # 4 = Red
  vgaDriver.setLineColor(2, LINEHEIGHT * 2, LINEHEIGHT * 4)
  # 2 = Green
  vgaDriver.setLineColor(1, LINEHEIGHT * 4, LINEHEIGHT * 6)
  # 1 = Blue
  vgaDriver.setLineColor(3, LINEHEIGHT * 6, LINEHEIGHT * 8)
  # 3 = Cyan
  vgaDriver.setLineColor(5, LINEHEIGHT * 8, LINEHEIGHT * 10)
  # 5 = Magenta
  vgaDriver.setLineColor(6, LINEHEIGHT * 10, LINEHEIGHT * 12)
  # 6 = Yellow
  vgaDriver.setLineColor(7, LINEHEIGHT * 12, LINEHEIGHT * 14)
  # 7 = White

setup()
while True:
  loop()
